# This file was generated by GoReleaser. DO NOT EDIT.
cask "ronja" do
  version "0.29.2"

  on_macos do
    on_arm do
      sha256 "06b4c2098fa3bf5b6990bab2b8af9c7a07c3ec7cb9f4598e21a7d253026aebad"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "761149ba4678b16e6507c9b8d162638078e1152cb5c748960958fd42a27d994b"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2aeb7cc872cbbfadaff6dd9b2b900e316763003872a83e1bfe357e8dc34e127b"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cf0958e5a57905e3dd41d42d1615446157bd18742ab601340968361729c6240b"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ronja"
  desc "Command-line access to Ronja — sign in, then work against the API over plain HTTP"
  homepage "https://ronja.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ronja"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ronja"]
    end
  end

  # No zap stanza required
end
