# This file was generated by GoReleaser. DO NOT EDIT.
cask "ronja" do
  version "0.29.0"

  on_macos do
    on_arm do
      sha256 "8a3f88389721465cde913b6ad75092efaaaa66b3ed197e38783f9cb8e0a2b810"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "56586ae2a495f1955972d4a75ccb5b908292441f3bec330db953185ead17ce4c"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "844c7f4f77ae35596477cab3243bf7513b8853a3fcb9bbd885229209fb1c95c7"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e070ede77f1624ec087097ec7cad97ce39edfc89711fcee46771f862c3d13f0d"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ronja"
  desc "Command-line access to Ronja — sign in, then work against the API over plain HTTP"
  homepage "https://ronja.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ronja"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ronja"]
    end
  end

  # No zap stanza required
end
