# This file was generated by GoReleaser. DO NOT EDIT.
cask "ronja" do
  version "0.31.1"

  on_macos do
    on_arm do
      sha256 "94b51c04b30116be52c1a1f2dcfc4a1a01ec9fa3811f40f04195a043460607c5"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58bd3da5972f15276bdb76ebf05e1a3f5420bafc2886943042c95062be566700"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "681731cb1c60f0a094deefcc47be4c42db233537711932c6f72ec2af94f6ca5c"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f5794de83c16589ad126e2fb66f5098344625dc3c28ecfbf41ca435e38027378"
      url "https://github.com/ronjatech/ronja-cli/releases/download/v#{version}/ronja_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ronja"
  desc "Command-line access to Ronja — sign in, then work against the API over plain HTTP"
  homepage "https://ronja.tech"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ronja"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ronja"]
    end
  end

  # No zap stanza required
end
